spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none} # 운영에선 none이나 validate로 바꾸기 위해 변수 처리
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${AUTH_REDIS_HOST:localhost}
      port: ${AUTH_REDIS_PORT:6378}
      password: ${REDIS_PASSWORD}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms

server:
  port: ${AUTH_SERVER_PORT:8000}

eureka:
  client:
    enabled: false # Eureka 클라이언트 기능 자체를 끕니다.
    register-with-eureka: false # 서버에 등록하지 않음
    fetch-registry: false # 서버로부터 정보를 가져오지 않음
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRED:3600000}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRED:604800000}

auth:
  concurrent:
    max-sessions: ${AUTH_MAX_CONCURRENT_SESSIONS:3}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      redis:
        enabled: false  # Redis가 죽어도 전체 앱을 DOWN 시키지 않음
      db:
        enabled: false     # DB가 죽어도 전체 앱을 DOWN 시키지 않음
    prometheus:
      access: unrestricted
  tracing:
    enabled: false
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}

    zipkin:
      tracing:
        enabled: false
        endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
