spring:
  application:
    name: queue-service

  kafka:
    # 환경변수 KAFKA_BROKERS가 있으면 그걸 쓰고, 없으면 로컬값(localhost:9092) 사용
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}  # 로컬 개발 환경 기준 (Docker 내부 통신 시 kafka:29092)
    properties:
      # [중요] MSK Serverless는 무조건 SASL_SSL + IAM 사용
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
    consumer:
      group-id: queue-service-group   # 컨슈머 그룹 ID (중요)
      auto-offset-reset: latest       # 가장 최신 메시지부터 읽음
      spring.json.trusted.packages: "*" # 모든 패키지의 객체를 신뢰하고 역직렬화 허용
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # JSON으로 받을거면 JsonDeserializer 사용 가능하지만, String으로 받아 직접 파싱하는게 디버깅에 유리함

  data:
    redis:
      host: ${QUEUE_REDIS_HOST}
      port: ${QUEUE_REDIS_PORT}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update} # 운영에선 none이나 validate로 바꾸기 위해 변수 처리
    properties:
      hibernate:
        default_schema: queue_schema
        format_sql: true
        use_sql_comments: true
    show-sql: ${SHOW_SQL:true} # 운영에선 로그 너무 많이 찍히니 false로 끄기 위해

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0