spring:
  application:
    name: timedeal-service
  cloud:
    service-registry:
      auto-registration:
        enabled: false
  data:
    redis:
      host: ${TIMEDEAL_REDIS_HOST:localhost}
      port: ${TIMEDEAL_REDIS_PORT:6382}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none} # 운영에선 none 권장됨
    show-sql: ${SHOW_SQL:false} # 운영에선 로그 너무 많이 찍히니 false로 끄기 위해
    properties:
      hibernate:
        format_sql: true
        default_schema: time_deal_schema
  sql:
    init:
      mode: ${SQL_INIT_MODE:never} # 기본은 안 함. 로컬에서만 환경변수로 always 주입. 매번 초기화 스크립트 실행하는 문제 발생 (data.sql, schema.sql)
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}


server:
  port: ${TIMEDEAL_SERVER_PORT:8030}

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}  # AWS에서는 false
    register-with-eureka: false
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}

    zipkin:
      tracing:
        enabled: false
        endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}