server:
  port: ${USER_SERVER_PORT:8060}
  servlet:
    context-path: /api/v1/users  # ALB가 넘겨주는 경로와 맞춰줍니다.

spring:
  application:
    name: user-service
  cloud:
    service-registry:
      auto-registration:
        enabled: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none} # 운영에선 none 권장됨
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
  data:
    redis:
      host: ${USER_REDIS_HOST:localhost}
      port: ${USER_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    properties:
      # [중요] MSK Serverless는 무조건 SASL_SSL + IAM 사용
      security.protocol: SASL_SSL
      sasl.mechanism: AWS_MSK_IAM
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
    consumer:
      group-id: point-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
      host: ${USER_REDIS_HOST:localhost}
      port: ${USER_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

eureka:
  client:
    # 유레카 클라이언트 자체를 끄기 (가장 확실)
    register-with-eureka: false
    fetch-registry: false
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}

    zipkin:
      tracing:
        endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}

logging:
  level:
    org.apache.kafka: ERROR # cloudwatch 불필요한 로그 쌓이는 것 방지 목적
    org.springframework.kafka: ERROR
