spring:
  application:
    name: order-service

  batch:
    jdbc:
      initialize-schema: never
      table-prefix: order_schema.BATCH_
    job:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${USER_REDIS_HOST:localhost}
      port: ${USER_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: order_schema

  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations:
        - classpath:schema.sql
        - classpath:sql/batch-schema.sql

  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: order-service
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
#      enable-auto-commit: true
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    # 재시도 설정 추가
    listener:
      ack-mode: record # 메시지 단위로 commit

    # 에러 핸들링 설정
    retry:
      max-attempts: 3 # 최대 3번 재시도
      backoff:
        initial-interval: 1000 # 첫 재시도: 1초 후
        multiplier: 2.0 # 재시도 간격: 1초 → 2초 → 4초
        max-interval: 10000 # 최대 10초

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,scheduledtasks
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}

  prometheus:
    metrics:
      export:
        enabled: true
