description = 'User Service for rush-deal Project'

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// eureka
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

	// jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// database
	runtimeOnly 'org.postgresql:postgresql'

	// validation
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// 자체 공통 모듈
	implementation 'com.github.RushCrew:rush-deal-common:v0.0.7'
	// security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	testImplementation 'org.springframework.security:spring-security-test'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
